<section id="banner_alternative_page">
    <div class="wrapper">
      <h1><?=$name;?></h1>
    </div>
  </section>


  <section id="brands">
    <div class="wrapper">
      <ul>
        <li class="one"><img src="assets/img/ferrari.png" alt=""></li>
        <li class="two"><img src="assets/img/audi.png" alt=""></li>
        <li class="three"><img src="assets/img/honda.png" alt=""></li>
        <li class="four"><img src="assets/img/infiniti.png" alt=""></li>
        <li class="five"><img src="assets/img/lexus.png" alt=""></li>
        <li class="six"><img src="assets/img/mbenz.png" alt=""></li>
      </ul>
    </div>
  </section>


  <section id="page">
    <div class="wrapper">
      <div class="content">
        <h3><?=$name;?></h3>
        <?=$_content;?>
      </div>
    </div>
  </section>