<section id="banner">
    <div class="wrapper">
      <h1>Witamy w RENT CAR</h1>
      <p>Poznański oddział wypożyczalni samochodów osobowych RentCar oferuje wynajem oparty na wielu korzyściach. Dostępne tu rozwiązania są w pełni nakierunkowane na indywidualne potrzeby klientów poszukujących najlepszej wypożyczalni samochodów na terenie Poznania.</p>
      <button class="btn-rezerwacja">Rezerwacja</button>
      <a href="#features"><button class="btn-wiecej">Dowiedz się więcej</button></a>
    </div>
  </section>


  <section id="brands">
    <div class="wrapper">
      <ul>
        <li><img src="assets/img/ferrari.png" alt=""></li>
        <li><img src="assets/img/audi.png" alt=""></li>
        <li><img src="assets/img/honda.png" alt=""></li>
        <li><img src="assets/img/infiniti.png" alt=""></li>
        <li><img src="assets/img/lexus.png" alt=""></li>
        <li><img src="assets/img/mbenz.png" alt=""></li>
      </ul>
    </div>
  </section>


  <section id="features">
    <div class="wrapper">
      <h2><span style="color:#00AEEF;font-size:35px">_</span>Dlaczego warto nas wybrać?</h2>
      <div class="cards">
        <div class="feature-card">
          <img src="assets/img/feature-card-icon.svg" alt="">
          <h3>Elastyczność</h3>
          <p>Niezależnie czy potrzebujesz auta na jeden dzień czy miesiąc zawsze zapewniamy konkurencyjne ceny.</p>
        </div>
        <div class="feature-card">
          <img src="assets/img/feature-card-icon.svg" alt="">
          <h3>Duży wybór</h3>
          <p>W naszej flocie oferowane są nawet najbardziej luksusowe pojazdy dla wymagających.</p>
        </div>
        <div class="feature-card">
          <img src="assets/img/feature-card-icon.svg" alt="">
          <h3>Bezproblemowość</h3>
          <p>Wymagamy minimum formalności. Cała procedura wydawania auta trwa zazwyczaj kilka minut.</p>
        </div>
      </div>
    </div>
  </section>


  <section id="our-offer">
    <div class="wrapper">
      <div class="our-offer-wrapper">
        <h2><span style="color:#00AEEF;font-size:35px">_</span>Nasza oferta</h1>
          <button class="our-offer-box" type="button">Wynajem krótkoterminowy</button>
          <div class="panel">Wynajem krótkoterminowy to usługa najmu samochodu od 1 do 30 dni. Procedury związane z uruchomieniem wynajmu krótkoterminowego są bardzo uproszczone i nie wymagają tak skomplikowanej analizy, jak ma to miejsce w przypadku finansowania pojazdów w leasingu bądź wynajmie długoterminowym. Czynsz usługi uwzględnia serwis, opony sezonowe, pełen pakiet usług ubezpieczeniowych wraz z rozliczeniem szkód komunikacyjnych oraz zapewnieniem samochodu zastępczego na czas awarii. </div>
          <button class="our-offer-box" type="button">Wynajem długoterminowy</button>
          <div class="panel">Wynajem długoterminowy jest połączeniem usługi „rent a car” oraz klasycznego leasingu operacyjnego, usługą polegającą na sprzedaży rozwiązań transportowych zamiast samochodów zarówno dla klientów indywidualnych jak i firm. Wynajem długoterminowy związany jest z użytkowaniem samochodu od 1 do 23 miesięcy. Usługa długoterminowa ze względu na dłuższą deklarację najmu jest atrakcyjniejsza cenowo niż wynajem krótkoterminowy. Procedury związane z jej rozpoczęciem są bardzo zbliżone i równie mało kłopotliwe, jak przy wynajmie poniżej 30 dni. Dzięki temu Klient w każdej chwili może wynająć, zmienić samochód bądź zrezygnować z usługi. Wynajem długoterminowy podobnie jak pozostałe wynajmy uwzględnia serwis, opony sezonowe, pełen pakiet usług ubezpieczeniowych wraz z rozliczaniem szkód komunikacyjnych oraz samochód zastępczy na czas awarii.</div>
          <button class="our-offer-box" type="button">Wynajem z OC sprawcy</button>
          <div class="panel">Osobom poszkodowanym w zdarzeniach drogowych, oprócz bezgotówkowej naprawy samochodu, należy się również wynajem auta zastępczego. Właśnie w takich przypadkach z pomocą przychodzi 99rent – specjalizujemy się m.in. w wynajmie samochodów zastępczych z OC sprawcy dla osób poszkodowanych w różnego rodzaju zdarzeniach drogowych. W przypadku braku możliwości korzystania z pojazdu, z powodu jego uszkodzenia z winy osoby trzeciej oraz likwidacji szkody z polisy OC sprawcy, możemy zaoferować Państwu kompleksowe usługi w ramach programu „SAMOCHÓD ZASTĘPCZY Z OC SPRAWCY” – oferujemy Państwu wynajem pojazdu zastępczego na czas likwidacji szkód.</div>
          <button class="our-offer-box" type="button">Auto z kierowcą</button>
          <div class="panel">Usługa wynajmu samochodu z kierowcą skierowana jest do najbardziej wymagających klientów ceniących bezpieczeństwo, prestiż oraz najwyższe standardy obsługi. Naszym klientom proponujemy samochody luksusowe prowadzone przez doświadczonych, odznaczających się wysoką kulturą osobistą oraz znajomością języków obcych kierowców.</br>
          Zapewniamy indywidualne, elastyczne i w pełni profesjonalne podejście do potrzeb każdego klienta, łącznie z odbiorem klienta z dowolnego miejsca i planowaniem najbardziej optymalnej trasy.
          </div>
      </div>
    </div>
  </section>


  <section id="money">
    <div class="wrapper">
      <h2>Cennik</h2>
      <p>Rezerwując za pośrednictwem strony internetowej otrzymujesz 15% zniżki.</p>
      <div class="money-box">
        <div class="money-item">
          <h1>199zł<span>DZIEŃ</span></h1>
          <h3>GRUPA A</h3>
          <p>Fiat Panda, Hyundai i10, Toyota Aygo, Škoda Citigo lub podobny</p>
          <button class="btn-rezerwacja">Rezerwacja</button>
        </div>
        <div class="money-item">
          <h1>224zł<span>DZIEŃ</span></h1>
          <h3>GRUPA B</h3>
          <p>Audi A1, BMW i3, Citroën C3, Hyundai i20 lub podobny</p>
          <button class="btn-rezerwacja">Rezerwacja</button>
        </div>
        <div class="money-item">
          <h1>250zł<span>DZIEŃ</span></h1>
          <h3>GRUPA D</h3>
          <p>Audi A4, BMW serii 3, Lexus IS, Skoda Superb lub podobny</p>
          <button class="btn-rezerwacja">Rezerwacja</button>
        </div>
        <div class="money-item">
          <h1>299zł<span>DZIEŃ</span></h1>
          <h3>GRUPA E</h3>
          <p>Audi A6, Honda Legend, Lexus GS, Volvo S90 lub podobny</p>
          <button class="btn-rezerwacja">Rezerwacja</button>
        </div>
      </div>
    </div>
  </section>


  <section id="contact">
    <div class="wrapper">
        <h3><a href="">Kliknij aby skontaktować się z nami</a></h3>
    </div>
  </section>