
<main class="wrapper" style="margin-top:50px;" >
    <form method="post" action="<?=$url;?>" >
        <table>
            <tr>
                <td>Login: </td>
                <td>
                    <input type="text" name="login[login]" value="<?=$login;?>" />
                </td>
            </tr>
            <tr>
                <td>Hasło: </td>
                <td>
                    <input type="password" name="login[password]" />
                </td>
            </tr>
            <tr>
                <td colspan="2" >
                    <input type="submit" name="login-form" value="Zaloguj" />
                </td>
            </tr>
        </table>
    </form>
</main>
