<section id="banner_alternative_page">
    <div class="wrapper">
      <h1>Dla pracowników</h1>
    </div>
  </section>


  <section id="brands">
    <div class="wrapper">
      <ul>
        <li class="one"><img src="assets/img/ferrari.png" alt=""></li>
        <li class="two"><img src="assets/img/audi.png" alt=""></li>
        <li class="three"><img src="assets/img/honda.png" alt=""></li>
        <li class="four"><img src="assets/img/infiniti.png" alt=""></li>
        <li class="five"><img src="assets/img/lexus.png" alt=""></li>
        <li class="six"><img src="assets/img/mbenz.png" alt=""></li>
      </ul>
    </div>
  </section>


  <section id="login_page">
    <div class="wrapper">
      <div class="info">
        <h3>Wewnętrzny wynajem aut pracownikom</h3>
        <p>Każdy pracownik naszej firmy ma możliwość wypożyczenia dowolnego auta za darmo.<br>Aby rozpocząć procedurę zaloguj się.</p>
      </div>
    </div>
  </section>


  <section id="login_form">
    <div class="wrapper">
      <div class="login-wrapper">
       <form class="form-signin" method="post" action="<?=$core['url'];?>">
         <h2 class="form-signin-heading">Logowanie</h2>
         <input type="text" class="form-control" name="login[login]" value="<?=$post['login'];?>" placeholder="Login" required="" autofocus="" />
         <input type="password" class="form-control" name="login[password]" placeholder="Hasło" required=""/>
         <button class="btn" type="submit" name="login-form" value="Zaloguj">Zaloguj</button>
       </form>
     </div>
    </div>
  </section>